### PR TITLE
updates for libp2p v0.22

### PR DESCRIPTION
**Pull request by willscott**
should use versioned deps after

https://github.com/ipfs/go-peertaskqueue/pull/25
https://github.com/ipfs/go-ipfs-routing/pull/36

* [ ] needs update of CI test versions to not be against go v1.16 anymore

### CODE REVIEW

**Comment by willscott** [comment]
is this a new test becoming flaky with these dependency updates?
```
=== RUN   TestCancellationQueryInProgress
      responsemanager_test.go:161: 
          	Error Trace:	/home/runner/work/go-graphsync/go-graphsync/responsemanager/responsemanager_test.go:161
          	Error:      	[]string{"processRequests(0)", "processRequests(1)"} does not contain "response(0)->abortRequest(0)"
          	Test:       	TestCancellationQueryInProgress
  --- FAIL: TestCancellationQueryInProgress (0.02s)
```

**Comment by willscott** [comment]
Additional note: required github checks will need to be updated with this change to point to the newer golang versions

**Comment by rvagg** [comment]
TestGraphsyncRoundTripIgnoreNBlocks  flaky documented @ https://github.com/ipfs/go-graphsync/issues/379 and was blocking the unified-ci upgrade. I was holding off https://github.com/ipfs/go-graphsync/pull/378 because I didn't want such a badly flaky test to be introduced as we've already got a few to deal with here and this one seems particularly flaky.

TestCancellationQueryInProgress I don't recall being flaky, but since it's failing on the tracing then I'm inclined to believe it was—there's a few tests where the tracing is a bit too strict and they need to be wound back a bit.

**Comment by rvagg** [comment]
Other than TestGraphsyncRoundTripIgnoreNBlocks this lgtm, I'm just not super keen on pushing ahead without figuring out why that one's so bad, or coming up with a strategy to stop it being such a problem for CI going forward. I think it's only for x86 so if there's a way to skip it for that then that's probably fine.

**Review by hannahhoward — APPROVED** [review]
LGTM

**Pull request merged**
